import type { Metadata } from "next";
import "./globals.css";
import "./styles.css";

import favicon from './favicon.ico';
import { ConfigProvider } from "antd";
import BaseTemplate from "@/components/base-template";

export const metadata: Metadata = {
  title: "Efektenang Portfolio Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConfigProvider
      theme={{
        token: {
          colorPrimary: '#1989AC'
        }
      }}
    >
      <html lang="en">
        <link rel="icon" type="image/x-icon" href={favicon.src} />
        <title>Efektenang Portofolio</title>
        <body><BaseTemplate>{children}</BaseTemplate></body>
      </html>
    </ConfigProvider>
  );
}
